/**
 * StoryFooter.tsx — Elegant story footer with generation metadata
 */
import { useState } from 'react';
import type { StoryMetadata } from './useStoryData';

interface StoryFooterProps {
  meta: StoryMetadata;
}

export function StoryFooter({ meta }: StoryFooterProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error(e);
    }
  };

  const totalTokens = (meta.prompt_tokens || 0) + (meta.completion_tokens || 0);

  return (
    <div className="relative">
      {/* Separator line */}
      <div
        className="w-full mb-12 rounded-full"
        style={{
          height: 1,
          background: 'linear-gradient(to right, transparent, var(--border-color), transparent)',
        }}
      />

      {/* Stats row */}
      <div className="flex flex-wrap justify-center gap-8 mb-10">
        {[
          { label: 'Model', value: meta.model_used.split('/').pop() || meta.model_used, icon: '🤖' },
          { label: 'Tokens', value: totalTokens > 0 ? totalTokens.toLocaleString() : '—', icon: '💬' },
          { label: 'Generation', value: `${meta.generation_duration_seconds.toFixed(1)}s`, icon: '⚡' },
          { label: 'Repository', value: `${meta.repo_owner}/${meta.repo_name}`, icon: '📦' },
        ].map((stat) => (
          <div key={stat.label} className="text-center">
            <div className="text-2xl mb-1">{stat.icon}</div>
            <div
              className="text-xs font-semibold tracking-widest uppercase mb-1"
              style={{ color: 'var(--text-secondary)', opacity: 0.6 }}
            >
              {stat.label}
            </div>
            <div
              className="font-mono text-sm font-medium"
              style={{ color: 'var(--text-primary)' }}
            >
              {stat.value}
            </div>
          </div>
        ))}
      </div>

      {/* Action buttons */}
      <div className="flex flex-wrap justify-center gap-4 mb-10">
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm text-white transition-all duration-300 hover:scale-105 active:scale-95 print:hidden"
          style={{
            background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
            boxShadow: '0 4px 20px rgba(99,102,241,0.4)',
          }}
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path strokeLinecap="round" strokeLinejoin="round" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M9 19l3 3m0 0l3-3m-3 3V10" />
          </svg>
          Export as PDF
        </button>

        <button
          onClick={handleCopy}
          className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm transition-all duration-300 hover:scale-105 active:scale-95 print:hidden"
          style={{
            background: 'var(--bg-secondary)',
            border: '1px solid var(--border-color)',
            color: 'var(--text-primary)',
          }}
        >
          {copied ? (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#10b981" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
              </svg>
              <span style={{ color: '#10b981' }}>Copied!</span>
            </>
          ) : (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              Share Link
            </>
          )}
        </button>
      </div>

      {/* Branding */}
      <div className="text-center">
        <p className="text-sm" style={{ color: 'var(--text-secondary)', opacity: 0.5 }}>
          Generated by{' '}
          <span
            className="font-bold"
            style={{
              background: 'linear-gradient(135deg, #6366f1, #ec4899)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}
          >
            Repponator
          </span>
          {' '}· Powered by CodeAutopsy
        </p>
      </div>
    </div>
  );
}
